spring.application.name=workshop-mongo

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=springboot
spring.mongodb.username=admin
spring.mongodb.password=root123
spring.mongodb.authentication-database=admin